### ISSUE TITLE
Console Error

### ISSUE THREAD

**Issue by hyWse** [danielntech/miniaturepets#26]
Every second, i get the following error:

```
> [20:22:50 WARN]: java.lang.NoSuchFieldException: networkManager
> [20:22:50 WARN]: at java.lang.Class.getDeclaredField(Class.java:2070)
> [20:22:50 WARN]: at com.kirelcodes.miniaturepets.utils.ף.ח(NMSClassInteracter.java:191)
> [20:22:50 WARN]: at com.kirelcodes.miniaturepets.utils.ף.getDeclaredField(NMSClassInteracter.java:179)
> [20:22:50 WARN]: at com.kirelcodes.miniaturepets..??ע???????????????????????????????????????????י?????????????????????ט??????????ו??ץ??א??????????????.כה.getNetworkManager(PacketInjector.java:60)
> [20:22:50 WARN]: at com.kirelcodes.miniaturepets..??ע???????????????????????????????????????????י?????????????????????ט??????????ו??ץ??א??????????????.כה.addPlayer(PacketInjector.java:41)
> [20:22:50 WARN]: at com.kirelcodes.miniaturepets..??ע???????????????????????????????????????????י?????????????????????ט??????????ו??ץ??א??????????????.טש.onPlayerJoin(CoreListener.java:458)
> [20:22:50 WARN]: at sun.reflect.GeneratedMethodAccessor123.invoke(Unknown Source)
> [20:22:50 WARN]: at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
> [20:22:50 WARN]: at java.lang.reflect.Method.invoke(Method.java:498)
> [20:22:50 WARN]: at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:302)
> [20:22:50 WARN]: at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:62)
> [20:22:50 WARN]: at org.bukkit.plugin.SimplePluginManager.fireEvent(SimplePluginManager.java:500)
> [20:22:50 WARN]: at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:485)
> [20:22:50 WARN]: at net.minecraft.server.v1_12_R1.PlayerList.onPlayerJoin(PlayerList.java:346)
> [20:22:50 WARN]: at net.minecraft.server.v1_12_R1.PlayerList.a(PlayerList.java:166)
> [20:22:50 WARN]: at net.minecraft.server.v1_12_R1.LoginListener.b(LoginListener.java:159)
> [20:22:50 WARN]: at net.minecraft.server.v1_12_R1.LoginListener.e(LoginListener.java:57)
> [20:22:50 WARN]: at net.minecraft.server.v1_12_R1.NetworkManager.a(NetworkManager.java:233)
> [20:22:50 WARN]: at net.minecraft.server.v1_12_R1.ServerConnection.c(ServerConnection.java:140)
> [20:22:50 WARN]: at net.minecraft.server.v1_12_R1.MinecraftServer.D(MinecraftServer.java:845)
> [20:22:50 WARN]: at net.minecraft.server.v1_12_R1.DedicatedServer.D(DedicatedServer.java:406)
> [20:22:50 WARN]: at net.minecraft.server.v1_12_R1.MinecraftServer.C(MinecraftServer.java:679)
> [20:22:50 WARN]: at net.minecraft.server.v1_12_R1.MinecraftServer.run(MinecraftServer.java:577)
> [20:22:50 WARN]: at java.lang.Thread.run(Thread.java:748)
```

**Comment by danielntech** [comment]
Hi, sorry for the delayed response.
Do you use SQL?

**Comment by hyWse** [comment]
Yes

**Comment by danielntech** [comment]
Unless you are running MiniaturePets between multiple servers (Bungeecord) then you shouldn't use SQL.

**Comment by hyWse** [comment]
We re running miniature pets on a network

**Comment by danielntech** [comment]
I see, please send me the output of the command `/mpet dump` and I'll forward this to our developers.

**Comment by hyWse** [comment]
https://pastebin.com/07HZE1MS

**Comment by danielntech** [comment]
I'll pass this over to our team, thanks for your report.

**Comment by danielntech** [comment]
Please update to version 2.0, it should be resolved now.

**Comment by hyWse** [comment]
Updated to version 2.0, error still occurs. Today my server seems to have crashed completely. Here again a log:
https://text.hywse.eu/view.php?url=MDJlNz&la=bash

**Comment by danielntech** [comment]
Are you using MySQL with MiniaturePets?

**Comment by danielntech** [comment]
* And what Spigot version are you running? Be exact please.

**Comment by hyWse** [comment]
Yes, I'm using MiniaturePets with MySQL (MariaDB)
Server: CraftBukkit version git-Spigot-2cf50f0-2b93d83 (MC: 1.12.2) (Implementing API version 1.12.2-R0.1-SNAPSHOT)
MPets: 2.0.2

**Comment by danielntech** [comment]
Please upgrade MPets to version 2.0.3

**Comment by danielntech** [comment]
I'll forward this to our team.

**Comment by NacOJerk** [comment]
Can you please update and send me a /mpet dump
