### ISSUE TITLE
PET NOT REMOVED ON server RESTART/STOP

### ISSUE THREAD

**Issue by Golicraft** [danielntech/miniaturepets#72]
*Short description:* 
The armorstands doesn't remove on server restart/stop!

*Long description:* 
When the server stops/restart and the player with a pet is online the armor stands from the pet won't be removed and will stay on the server FOREVER
example: https://gyazo.com/1180b6b1e3095b705df1e6489d17af74

*Actions to repeat / ways of reaching the bug:* 
Paperspigot 1.8.8
ProtocolLib 3.6.4
MiniaturePets 2.1.2

*Miniature Pets Dump Link:*
Won't send because I don't want to share my plugins. Please respect that

**Comment by Shadume** [comment]
Hi, I don't know how to prevent this bug, but I've the same and in case other people have the same problem, I found how to get rid of it.
First, when you right click on the static pet with empty hand, it will remove the pets blocks, block by block.
But when you finally get rid of all blocks, the invisible armorstand still here, and if make the mistake of clicking on it with a block in your hand, it will place the bloc on the armorstand, again...
So, you have to do this command : /kill @e[type=ArmorStand,c=1]
Or this one : /kill @e[type=ArmorStand,r=3]
For me these commands doesn't worked, I don't know if we have to be really on the armorstand, or look at it, so I just did /kill @e , because I don't care about entities on my serv x)
I hope that'll help

**Comment by Golicraft** [comment]
> Hi, I don't know how to prevent this bug, but I've the same and in case other people have the same problem, I found how to get rid of it.
> First, when you right click on the static pet with empty hand, it will remove the pets blocks, block by block.
> But when you finally get rid of all blocks, the invisible armorstand still here, and if make the mistake of clicking on it with a block in your hand, it will place the bloc on the armorstand, again...
> So, you have to do this command : /kill @e[type=ArmorStand,c=1]
> Or this one : /kill @e[type=ArmorStand,r=3]
> For me these commands doesn't worked, I don't know if we have to be really on the armorstand, or look at it, so I just did /kill @e , because I don't care about entities on my serv x)
> I hope that'll help

Thank you for taking your time to reply and help. I already use that command, thanks but it isn't a good solution on long term.

**Comment by NacOJerk** [comment]
Hey Im aware of this bug, this will happened if the mpet plugin is not disabled correctly.

Because we moved to use EntityAttributes as a way to store data. Now if the plugin is not disabled correctly than it won't remove all the entities with the given attribute. When the server loads again it looks at the attribute and ignores it so I can't remove the pets on startup.
What I might do is create a plugin that will load on startup (MPet can't be loaded on startup) and this plugin will deal with removing the bad pets. But it is not the best solution

**Comment by NacOJerk** [comment]
I will decide on a solution until Saturday

**Comment by Golicraft** [comment]
I'll tested the newest version. The pet still doesn't get removed sadly. Thank you in advance

**Comment by danielntech** [comment]
We haven't resolved this manner yet.
@NacOJerk will keep this updated.

**Comment by danielntech** [comment]
This was fixed in the latest update.

**Comment by Golicraft** [comment]
> This was fixed in the latest update.

I tested it out. Not fixed and yes, I have turn "PetExtraRemoval: true" in config.yml
